@startuml "acme"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/react.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/go.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/mysql.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/redis.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome/bank.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5/users.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5/user.puml

skinparam wrapWidth 200
skinparam maxMessageSize 100

Person(customer, "Customer", "", $sprite="user")
Person(shipping_team, "Shipping/warehouse Team", "", $sprite="users")

System(payment_provider, "Payment Provider", "", "", $sprite="bank")


Container(frontend, "Web UI", "React", "Serves customer", $sprite="react")

!include frontend_components.puml

Enterprise_Boundary(acme, "ACME Services") {
'Components.
    !include cart_components.puml
    !include auth_components.puml
    !include goods_components.puml
    !include order_components.puml
    !include payment_components.puml
}

'Relations.
!include cart_relations.puml
!include auth_relations.puml
!include frontend_relations.puml
!include goods_relations.puml
!include order_relations.puml
!include payment_relations.puml

@enduml
